### ISSUE TITLE
scrollbar resize perturbs visualization in word wrap mode

### ISSUE THREAD

**Issue by franko** [pragtical/pragtical#10]
When the cursor hover close to the scrollbar the scrollbar is made bigger but, when displaying the file content in word-wrap mode the flow of the text changes which is very annoying.

As an user my expectation is that the enlarging of the scrollbar should not affect the flow of the text which is shown on the editor.

**Comment by jgmdev** [comment]
The line wrapping plugin is a can of bugs and surely needs some fixes. Doesn't behaves properly with some plugins and it seems that as of late it also breaks syntax rendering in some circumstances. Those are some of the reasons I don't even use it.

I fixed the issue as referenced on the linked PR by always subtracting the full expanded size of the scrollbar, let me know if that works for you.

**Comment by franko** [comment]
Thank you for looking at that. Yes, the fix works, it is just a little bit strange in word-wrap mode because the space taken by the enlarged scrollbar is no longer use but that's a minor quirk. Everything is fine otherwise.

**Comment by jgmdev** [comment]
Ok, will merge as is for the moment, thanks for the feedback
