### ISSUE TITLE
Support the Scoop package manager for windows.

### ISSUE THREAD

**Issue by AmerM137** [pragtical/pragtical#123]
Hi there! Thank you for the wonderful additions to the (already great) lite-xl editor.

Any chance you can support the scoop package manager for windows just like lite-xl? I've been using scoop for most of my single-executable programs as well as editors like Neovim.

**Comment by jgmdev** [comment]
Was looking into this and it seems you would have to make a contribution into this repository https://github.com/ScoopInstaller/Extras Maybe you can open a Pull Request on that repo adding pragtical, you can use this file as a template: https://github.com/ScoopInstaller/Extras/blob/master/bucket/lite-xl.json

**Comment by AmerM137** [comment]
Sounds good, I'll do that soon.

**Comment by AmerM137** [comment]
Pull request submitted to scoop/extras -> https://github.com/ScoopInstaller/Extras/pull/13763

**Comment by jgmdev** [comment]
It seems your PR was merged into the Extras repository! Added scoop to the windows setup guide https://pragtical.dev/docs/setup/windows#scoop thank you!
