### ISSUE TITLE
aarch64 packages

### ISSUE THREAD

**Issue by jvoisin** [pragtical/pragtical#130]
It would be nice to provide aarch64 builds of pragtical, since not everyone is using x86_64 :)

**Comment by k8ieone** [comment]
I'm considering making a Flatpak for Pragtical. Flatpak works on ARM as well. My guess is you'd like a binary same as on x86, so it's probably not the ultimate answer here, more like another option.

I'll open a separate issue for this, I just wanted to shoot it out there.

@jgmdev Would you be ok with having Pragtical published on Flathub?

**Comment by jgmdev** [comment]
> @jgmdev Would you be ok with having Pragtical published on Flathub?

Why not? feel free to make a Flatpak the more the merrier :fireworks: 

Also will merge the linked PR should provide portable and appimage linux builds for aarch64, wanted this my self too for some time.
