### ISSUE TITLE
Pragtical terminal command hangs

### ISSUE THREAD

**Issue by aziis98** [pragtical/pragtical#131]
Differently from Sublime or VSCode, when I call `pragtical .` from the terminal it hangs the session until I close pragtical. It would be nice if by default this worked like for example sublime that has a `--wait` option to trigger the "until editor closed" behaviour. 

I searched the settings and the docs but I only found the IPC plugin but I don't think its settings are related with this.

**Comment by jgmdev** [comment]
What do you think about #132? Can you test it? I know it is not the same but currently it is easier to implement. One can use an alias on your shell profile that automatically invokes pragtical with the `-f` flag, something like:

```sh
alias p="pragtical --fork"
```
So when typing `p /path/to/project`the editor is launched on a separate process.

**Comment by aziis98** [comment]
This looks reasonable thanks! I compiled your pull request locally and it works flawlessly

**Comment by jgmdev** [comment]
Cleaned some mistakes and merged the PR, the new feature should be available on next release.

Thanks for the feedback!
