### ISSUE TITLE
scoop install not working: Couldn't find manifest for 'pragtical'.

### ISSUE THREAD

**Issue by mike-rambil** [pragtical/pragtical#144]
Installing pragtical via powershell not working in windows.

I tried following the installation from the [docs](https://pragtical.dev/docs/setup/windows) but it seems to be not working. 

![image](https://github.com/user-attachments/assets/0f568c7e-c96b-41df-84c1-12e85939f56c)

**Comment by jgmdev** [comment]
I'm not familiar with scoop my self but maybe running this:

```
scoop bucket add extras
```

Then try again with `scoop install pragtical` if that works the website docs will need an update.

**Comment by mike-rambil** [comment]
Thanks it worked!

**Comment by mike-rambil** [comment]
Thanks it worked!!
