### ISSUE TITLE
Can we have vim inbuilt?

### ISSUE THREAD

**Issue by mike-rambil** [pragtical/pragtical#145]
I am not a person that tries out a lot of new code editors but this one seems to be extremely appealing to me.

I love this code editor. 

Its extremely fast but however after looking at the documentation - I come to find that this editor doesn't have built in vim.

**Comment by jgmdev** [comment]
Check this comment out https://github.com/pragtical/plugins/issues/6#issuecomment-2308639372

Hopefully someone can make that plugin less invasive (or just write a simpler plugin borrowing some ideas from it) and just provide the modal editing capability without all the other things like messing the whole status bar, etc...
