### ISSUE TITLE
An internal error occurred in a critical part of the application. undefined MOD_VERSION 

### ISSUE THREAD

**Issue by mike-rambil** [pragtical/pragtical#146]
## Problem
Went to plugins and tried to right click on one of the plugins(it was "vibe" plugin for installing vim) and clicked on install. 

![image](https://github.com/user-attachments/assets/5b57337e-930b-43a5-81cf-f51fd04cbcde)

## Error Name:
![image](https://github.com/user-attachments/assets/01824607-4a03-40dc-a360-18f20183d92c)

## How it happened:
- Open Pragtical.
- Type "Plugin Manage: Show" and press enter.
- Go to all plugins view and right click on any of the plugins(in my case, "vibe" for vim) and click on install.
- And I got the error mentioned above.

## System Info:
![image](https://github.com/user-attachments/assets/09202221-281b-44d4-90dd-6d5021b7dcba)

**Comment by jgmdev** [comment]
Now it should be installable for reference: https://github.com/pragtical/pragtical/issues/145#issuecomment-2308659912 > https://github.com/pragtical/plugins/issues/6#issuecomment-2308639372
