### ISSUE TITLE
Widget submodule should be updated

### ISSUE THREAD

**Issue by dalz** [pragtical/pragtical#147]
I just installed the latest release (3.4.2) of pragtical on NixOS and the search_ui plugin fails to load. The reason seems to be that the widget submodule tracks an old commit that doesn't include searchreplacelist.lua.

**Comment by jgmdev** [comment]
As explained on the linked PR #148 we don't rely on the git submodule to provide the widgets anymore, instead we use meson to handle the project dependencies using subprojects.

Thanks for reporting and sorry for the confusion!
