### ISSUE TITLE
Arch rolling, X11, GLX error

### ISSUE THREAD

**Issue by dagelf** [pragtical/pragtical#160]
```
 Downloads]$ ./Pragtical-rolling-x86_64.AppImage 
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  158
  Current serial number in output stream:  159
```

**Comment by jgmdev** [comment]
Tested here and it works on XFCE X11/Wayfire(wayland), Gnome X11/Wayland. A google search revealed that maybe your system needs a restart: https://stackoverflow.com/questions/40644455/x-error-of-failed-request-badvalue-integer-parameter-out-of-range-for-operatio

**Comment by dagelf** [comment]
New to arch ...so thanks! Still getting to know the quirks.

**Comment by dagelf** [comment]
:blush:
