### ISSUE TITLE
feat: a recent files menu like Emacs' recentf

### ISSUE THREAD

**Issue by enderprism** [pragtical/pragtical#20]
would it be possible to implement something like Emacs' `recentf` menu? i'm trying out Pragtical from Doom Emacs.
https://www.emacswiki.org/emacs/RecentFiles

PS: keychords would be great but they aren't the subject of this issue :P

**Comment by jgmdev** [comment]
You mean something like the recent projects shown on screenshot but for files?

![welcome-recent](https://github.com/pragtical/pragtical/assets/1702572/77c64b5b-c51e-4593-9973-9d51b692bdb4)

or using the CommandView in the same way as ctrl+p?

**Comment by enderprism** [comment]
using the commandview (in my doom emacs config i do `Spc F R` and it runs recentf in the counsel)

**Comment by enderprism** [comment]
is this "Recent Projects" feature from more recent builds? i've never seen it before or idk how to toggle it on

**Comment by jgmdev** [comment]
Implemented the funcionality as a [recentfiles](https://github.com/pragtical/plugins/blob/master/plugins/recentfiles.lua) plugin, give it a try.

**Comment by enderprism** [comment]
i'll give it a try asap

**Comment by mart-on-windows** [comment]
I very much like your `recentfiles.lua` plugin but I feel it would benefit from a clear items/list capability.

I've been trying it with the following modifications and Lite XL:

1) Comment out lines 78 and 84 (`if #recent_files > 0 then` and the corresponding `end`) to allow an empty `recent_files` table to be saved.
Was the purpose of line 78 an optimization? 

2) Add command:
```lua
  ["core:open-recent-file-clear"] = function()
    while #recent_files > 0 do
      table.remove(recent_files, #recent_files)
    end
  end,
```

My understanding of Pragtical/Lite XL/Lua is pretty basic so it would be interesting to see how you would implement the feature.

**Comment by jgmdev** [comment]
> 1. Was the purpose of line 78 an optimization?

Basically not generating a file with empty content for unneeded reading on startup.

> 2\. Add command:

I would change it to:

```lua
  ["core:open-recent-file-clear"] = function()
    recent_files = {}
    os.remove(recent_files_path)
  end,
```
and leave lines 78 and 84 intact

**Comment by mart-on-windows** [comment]
Thanks, that looks like a better solution.

**Comment by jgmdev** [comment]
pushed the command to plugins repo https://github.com/pragtical/plugins/commit/28863cbb43c529b10d47048a9bddecef1202d935

**Comment by jgmdev** [comment]
Since this was implemented as a plugin will close this issue, feel free to send any improvement PR's for [recentfiles](https://github.com/pragtical/plugins/blob/master/plugins/recentfiles.lua) on the plugins repo.
