### ISSUE TITLE
Wrong replacement of backslashes belonging to multi-byte sequences in Shift_JIS

### ISSUE THREAD

**Issue by Hinaxnitro** [pragtical/pragtical#201]
The solution for #94 is having problem when multi-byte characters have character code of backslash.

![スクリーンショット 2024-10-16 134751](https://github.com/user-attachments/assets/2836993c-300e-4be9-9a04-ae660a0bd53c)

(text from [https://www.type-labo.jp/KumimihonREAD.html](https://www.type-labo.jp/KumimihonREAD.html))

changes mentioned at [the reply of my comment](https://github.com/pragtical/pragtical/issues/94#issuecomment-2417338893) caused error.

[error.txt](https://github.com/user-attachments/files/17401120/error.txt)

**Comment by jgmdev** [comment]
Please try this change instead and let me know if it works for you:

```diff
diff --git a/data/core/encoding.lua b/data/core/encoding.lua
index 51adf9e4..20f23e9b 100644
--- a/data/core/encoding.lua
+++ b/data/core/encoding.lua
@@ -9,7 +9,7 @@ encoding.convert = function(tocharset, fromcharset, text, options)
     -- we are insterested on keeping the original to prevent issues on
     -- code that uses escape sequences like '\n', '\r', etc...
     local errmsg
-    text = text:gsub("\\", "{\\\\\\}")
+    text = text:gsub("([%z\x01-\x59])(\\)", "%1{\\\\\\}")
     text, errmsg = encoding_convert(tocharset, fromcharset, text, options)
     if text then
       text = text:gsub("%{¥¥¥%}", "\\")
```

I tested locally and it is leaving multi-byte sequences intact while performing the \\ placeholder replacement on regular ASCII sequences but, who knows what other combination could give issues :)

**Comment by jgmdev** [comment]
I think I got it now, with this patch it should only match backslashes that aren't preceded by a starting multi-byte sequence:

```diff
diff --git a/data/core/encoding.lua b/data/core/encoding.lua
index 51adf9e4..fd2e6d04 100644
--- a/data/core/encoding.lua
+++ b/data/core/encoding.lua
@@ -9,7 +9,7 @@ encoding.convert = function(tocharset, fromcharset, text, options)
     -- we are insterested on keeping the original to prevent issues on
     -- code that uses escape sequences like '\n', '\r', etc...
     local errmsg
-    text = text:gsub("\\", "{\\\\\\}")
+    text = text:gsub("([^\x81-\x9f\xe0-\xef])(\\)", "%1{\\\\\\}")
     text, errmsg = encoding_convert(tocharset, fromcharset, text, options)
     if text then
       text = text:gsub("%{¥¥¥%}", "\\")
```

So now a sequence like 創作文の構造\n should properly get replaced with the placeholder for the yen iconv conversion while keep multi-byte sequences intact

**Comment by Hinaxnitro** [comment]
The text I tried to read is now shown correctly.

Thank you for fixing this problem.
