### ISSUE TITLE
bug: empty context menu

### ISSUE THREAD

**Issue by enderprism** [pragtical/pragtical#21]
when i right-click, an empty context menu pops up (always behind others context menus, but it's still there)
if it helps, i'm using the AUR package of pragtical (under the name `pragtical`) and i use the [catppuccin theme](https://github.com/Garbg/litexl-catppuccin) (which is probably soon to be added to the official repos) with it, even if it's made for LiteXL and not explicitely Pragtical.
```
Nom                      : pragtical
Version                  : 3.1.1-1
Description              : The practical and pragmatic code editor.
Architecture             : x86_64
URL                      : https://github.com/pragtical/pragtical
Licences                 : MIT
Groupes                  : --
Fournit                  : --
Dépend de                : luajit  sdl2  freetype2  pcre2  uchardet
                           hicolor-icon-theme
Dépendances opt.         : --
Requis par               : ppm-git
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 2,06 MiB
Paqueteur                : Unknown Packager
Compilé le               : dim. 10 sept. 2023 11:05:55
Installé le              : dim. 10 sept. 2023 11:06:11
Motif d’installation     : Explicitement installé
Script d’installation    : Non
Validé par               : --
```

it throws an error when trying to click on it (which doesn't cause a crash).
the error and the empty menu can be found below. i'll send the error as text if i figure out where to find the log file:
![image](https://github.com/pragtical/pragtical/assets/76617157/fdafecbc-248c-4a1e-8402-d73570e53573)

**Comment by enderprism** [comment]
here are all my installed plugins (output from `ppm list | grep "installed"`):

```
           align_carets |        0.1 |     plugin |          3 | installed
             autoinsert |        0.2 |     plugin |          3 | installed
               autosave |        0.1 |     plugin |          3 | installed
                  build |        0.1 |     plugin |          3 | installed
              centerdoc |        0.1 |     plugin |          3 | installed
               codeplus |        0.1 |     plugin |          3 | installed
           colorpreview |        0.2 |     plugin |          3 | installed
               debugger |        0.1 |     plugin |          3 | installed
       dragdropselected |        0.3 |     plugin |        3.1 | installed
                 exterm |        0.1 |     plugin |          3 | installed
      gitdiff_highlight |        0.1 |     plugin |          3 | installed
         indent_convert |        0.1 |     plugin |          3 | installed
            indentguide |        0.1 |     plugin |          3 | installed
                   json |        1.0 |    library |        n/a | installed
               lintplus |        0.3 |     plugin |          3 | installed
                    lsp |        0.6 |     plugin |        3.1 | installed
                  lsp_c |     16.0.2 |     plugin |          3 | installed
           lsp_snippets |          1 |     plugin |          3 | installed
                markers |        0.1 |     plugin |          3 | installed
                minimap |        0.2 |     plugin |          3 | installed
              nerdicons |        1.0 |     plugin |          3 | installed
         plugin_manager |        0.1 |     plugin |          3 | installed
            restoretabs |        0.1 |     plugin |          3 | installed
                    scm |        0.3 |     plugin |        3.1 | installed
     selectionhighlight |        0.2 |     plugin |          3 | installed
            smoothcaret |        0.3 |     plugin |        3.1 | installed
               snippets |          1 |     plugin |          3 | installed
          sticky_scroll |        1.0 |     plugin |          3 | installed
               terminal |        1.0 |     plugin |          3 | installed
```

**Comment by jgmdev** [comment]
This is an old bug that I totally forgot. It actually occurs when clicking a context menu dividers which are not real items. PR #22 should fix it, give it a try and let me know, otherwise I will merge it in a bit.

**Comment by enderprism** [comment]
the error disappears but the empty context menu remains. is is caused by pragtical or a plugin?

**Comment by jgmdev** [comment]
Ahh, so you are really getting an empty ghost ContextMenu, I thought the issue was misinterpreted since I can't reproduce it so yeah, it may be a plugin that is causing it. The plugins you have that I don't are:

* build
* codeplus
* debugger
* dragdropselected
* exterm
* gitdiff_highlight <- `scm` should already provide that functionality
* lsp_c
* plugin_manager
* restoretabs
* sticky_scroll

You can try disabling those plugins 1 by 1 and reloading the editor to see which one is causing the issue. Try disabling the plugins that make use of the ContextMenu first, like the plugin_manager, etc...

**Comment by jgmdev** [comment]
Was curious and yes it seems the plugin_manager was the culprit, changing the last lines of `plugin_manager/plugin_view.lua` to the following seems to fix the issue:

```lua
PluginView.menu:register(
  function()
    if core.active_view:is(PluginView) then
      return true
    end
    return false
  end, {
  { text = "Install", command = "plugin-manager:install-hovered" },
  { text = "Uninstall", command = "plugin-manager:uninstall-hovered" },
  { text = "View Source", command = "plugin-manager:view-source-hovered" },
  ContextMenu.DIVIDER,
  { text = "Refresh Listing", command = "plugin-manager:refresh-all" },
  { text = "Upgrade All", command = "plugin-manager:upgrade-all" },
})
```
I will report the issue upstream.

**Comment by jgmdev** [comment]
Referencing the upstream issue https://github.com/lite-xl/lite-xl-plugin-manager/issues/43

**Comment by enderprism** [comment]
alr, thanks for the help!
i have another quesition: how can i make pragtical verbose in the terminal? i have an issue with the build plugin (it doesn't do anything even if i have a makefile), but to open a good issue about it, i need to know what it's doing when i try to build my project. the issue is that nothing shows up in the log.

**Comment by jgmdev** [comment]
> i have an issue with the build plugin (it doesn't do anything even if i have a makefile)

My advise would be to contact the build plugin author which is Adam by opening an issue on https://github.com/adamharrison/lite-xl-ide and explaining the problem you are confronting.
