### ISSUE TITLE
Unexpected behaviour with lua snippets

### ISSUE THREAD

**Issue by kmafeni04** [pragtical/pragtical#29]
When selecting a snippet, it will place the expected text from the snippet but not remove what was written, instead it appends the snippet's text to the front  and leaves the old text

Video:
https://imgur.com/Eu6DXy8

**Comment by jgmdev** [comment]
While the snippets plugin has sometimes some issues resetting previous state and moves cursor to wrong places (https://github.com/vqns/lite-xl-snippets/issues/3) I can't reproduce your issue.

https://github.com/pragtical/pragtical/assets/1702572/1a6c4d80-c691-4ebc-98fb-ee65be0223fb

Are you running the latest versions of the plugins in question?

**Comment by kmafeni04** [comment]
> Are you running the latest versions of the plugins in question?

Yes, updated all plugins and using lsp and lsp_snippets plugins installed from the package manager then following the readme file in their individual folders

**Comment by jgmdev** [comment]
Try changing the default snippet key bindings from using the tab binding to something like:

![snippets-bindings](https://github.com/pragtical/pragtical/assets/1702572/14567886-f159-4903-bc90-d7425bb0085b)

Can you also apply this patch into lsp plugin to see if things improve?

```diff
diff --git a/init.lua b/init.lua
index f3384e0..d403c38 100644
--- a/init.lua
+++ b/init.lua
@@ -439,6 +439,7 @@ local function apply_edit(server, doc, text_edit, is_snippet)
 
   if is_snippet and snippets_found and config.plugins.lsp.snippets then
     doc:set_selection(line1, col1, line1, col1)
+    command.perform "snippets:exit"
     snippets.execute {format = 'lsp', template = text}
     return true
   end
@@ -559,6 +560,7 @@ local function autocomplete_onselect(index, item)
       local line2, col2 = doc:get_selection()
       local line1, col1 = doc:position_offset(line2, col2, translate.start_of_word)
       doc:set_selection(line1, col1, line2, col2)
+      command.perform "snippets:exit"
       snippets.execute {format = 'lsp', template = completion.insertText}
       return true
     end
```

**Comment by kmafeni04** [comment]
> Can you also apply this patch into lsp plugin to see if things improve?

Tried this and it didn't change anything, thank you though. Might be an issue with the way I have plugins installed, will try with a fresh config to find out

**Comment by kmafeni04** [comment]
Ok, after some digging, the action that runs the snippet is the autocomplete setting not the snippet setting. Not sure if this has anything to do with it but I'm not seeing the keyboard shortcuts on the snippet side doing anything

**Comment by kmafeni04** [comment]
Issue was solved by installing snippets plugin directly from GitHub rather than from plugin manager

**Comment by jgmdev** [comment]
> Issue was solved by installing snippets plugin directly from GitHub rather than from plugin manager

Thanks for reporting back! [Updated snippets and lsp_snippets](https://github.com/pragtical/plugins/commit/95a4b27d306609d5c0afd552412d45b2ce090c19) pointed commit on the plugins repository manifest file to prevent future users from experiencing the same.
