### ISSUE TITLE
Error when clicking View README in plugin manager

### ISSUE THREAD

**Issue by mundusnine** [pragtical/pragtical#35]
Using rolling release version on Arch Linux

![image](https://github.com/pragtical/pragtical/assets/29337013/e75bb8fc-d68d-4256-978f-6e4d279c784e)

![image](https://github.com/pragtical/pragtical/assets/29337013/514ae37c-c012-4c9c-bda6-b5dcd6523fbf)

**Comment by jgmdev** [comment]
Should be fixed on latest plugin manager code
