### ISSUE TITLE
Will there be an AUR package soon?

### ISSUE THREAD

**Issue by sokorototo** [pragtical/pragtical#65]
Nice project btw, I highly appreciate the app. I don't have much to say, just asking for an AUR package. Thanks in advance

**Comment by k8ieone** [comment]
@sokorototo There already is an AUR package.

`pragtical` - https://aur.archlinux.org/packages/pragtical
`pragtical-git` - https://aur.archlinux.org/packages/pragtical-git

**Comment by k8ieone** [comment]
No worries 😉
