### ISSUE TITLE
Toggle overwrite mode from numeric keypad

### ISSUE THREAD

**Issue by mart-on-windows** [pragtical/pragtical#72]
Suggested changes to `system.c` to get overwrite mode to work from the numeric keypad.

```c
static const char *numpad[] = { "end", "down", "pagedown", "left", "clear", "right", "home", "up", "pageup", "insert", "delete" };
```

I would also replace `""` with `"clear"` so this key might become useful. 

```
WINUSER.H Identifier	IBM−Compatible Keyboard
VK_CLEAR 		Numeric keyboard 5 with Num Lock OFF
```

**Comment by jgmdev** [comment]
Makes sense, thanks for the suggestion! Also feel free to submit PR's for stuff like this, so other peoples name appear on the commits log :smile:
