### ISSUE TITLE
Build Pragtical on MSYS2

### ISSUE THREAD

**Issue by ghost** [pragtical/pragtical#74]
Please help. The Mbedtls dependency is really annoying.

https://github.com/msys2/MINGW-packages/issues/20199

**Comment by jgmdev** [comment]
You can disable the plugin manager by passing `-Dppm=false` to the meson setup flags.

**Comment by iahung3** [comment]
> You can disable the plugin manager by passing `-Dppm=false` to the meson setup flags.

But this is only a temporary solution. I didn't try to build the Lite XL plugin manager. But I suspect it will also fail to build. LPM and PPM are basically the same.

**Comment by jgmdev** [comment]
> This is only a temporary solution. I didn't try to build the Lite XL plugin manager. But I suspect it will also fail to build. LPM and PPM are basically the same.

I can add an extra `static`  build flag for the ppm subproject to force static building of the binary if desired, for example:

```
meson setup -Dppm:static=true build
```
This would force building all necessary dependencies and linking to them statically. Let me know what you think, here is a patch implementing the idea in any case.

```diff
diff --git a/subprojects/packagefiles/ppm/meson.build b/subprojects/packagefiles/ppm/meson.build
index 667b4a68..0120bad1 100644
--- a/subprojects/packagefiles/ppm/meson.build
+++ b/subprojects/packagefiles/ppm/meson.build
@@ -14,7 +14,7 @@ endif
 
 if meson.get_compiler('c').get_id() == 'msvc'
     message('MSVC compiler not supported, use MSYS to build.')
-elif get_option('wrap_mode') != 'forcefallback'
+elif get_option('wrap_mode') != 'forcefallback' and not get_option('static')
     cc = meson.get_compiler('c')
 
     lua_exe = find_program('lua')
diff --git a/subprojects/packagefiles/ppm/meson_options.txt b/subprojects/packagefiles/ppm/meson_options.txt
index 1d8b4ea3..af22f45a 100644
--- a/subprojects/packagefiles/ppm/meson_options.txt
+++ b/subprojects/packagefiles/ppm/meson_options.txt
@@ -1,2 +1,3 @@
 option('data_dir', type : 'string', value : '/', description: 'Data directory of installation')
 option('arch_tuple', type : 'string', value : '', description: 'Specify a custom architecture tuple')
+option('static', type : 'boolean', value : false, description: 'Force building in static mode')
```

**Comment by iahung3** [comment]
I did try the `-f` switch in `build-packages.sh`. This basically builds everything statically from source. The problem is, MbedTls doesn't compile!

**Comment by iahung3** [comment]
Btw, MSYS2 only has packages for MbedTls 3, but you are using MbedTls 2.

**Comment by jgmdev** [comment]
> I did try the `-f` switch in `build-packages.sh`. This basically builds everything statically from source. The problem is, MbedTls doesn't compile!

I just gave it a try under msys2 using the shared patch, setting the `static` option to true and the plugin manager is properly built. Another option (which is used on the CI scripts when building on msys) and wouldn't require the patch is to set `--wrap-mode=forcefallback` .

Another alternative is to eliminate the need to add a new `static` option, detect if running under msys, and automatically compile statically without user intervention, this patch would look like:

```diff
diff --git a/subprojects/packagefiles/ppm/meson.build b/subprojects/packagefiles/ppm/meson.build
index 667b4a68..e8b33b0a 100644
--- a/subprojects/packagefiles/ppm/meson.build
+++ b/subprojects/packagefiles/ppm/meson.build
@@ -12,9 +12,11 @@ else
     arch_tuple = '@0@-@1@'.format(target_machine.cpu_family(), target_machine.system())
 endif
 
+is_msys = host_machine.system() == 'windows' and meson.get_compiler('c').get_id() == 'gcc'
+
 if meson.get_compiler('c').get_id() == 'msvc'
     message('MSVC compiler not supported, use MSYS to build.')
-elif get_option('wrap_mode') != 'forcefallback'
+elif get_option('wrap_mode') != 'forcefallback' and not is_msys
     cc = meson.get_compiler('c')
 
     lua_exe = find_program('lua')
```

> Btw, MSYS2 only has packages for MbedTls 3, but you are using MbedTls 2.

Yes, the only easy way is to automatically force a static binary build of the plugin manager. Unless, upstream ports the plugin manager to use newer mbedtls or msys provides an mbedtls2 package like ArchLinux is doing.

**Comment by iahung3** [comment]
Your patch worked. Can you integrate them into the source tree?
